# fly.toml app configuration file generated for yp-blog-api on 2024-09-01T13:14:35+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'yp-blog-api'
primary_region = 'sin'

[build]

[http_service]
  internal_port = 9090
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[mounts]
  source = "sqlife_volume"
  destination = "/data"

[[vm]]
  size = 'shared-cpu-1x'
